items:
    label: Item
    view:
        list: $/arteriaweb/catalog/models/item/columns.yaml
        toolbarButtons: create|delete
    manage:
        form: $/arteriaweb/catalog/models/item/fields.yaml
        list: $/arteriaweb/catalog/models/item/columns.yaml

kind:
    label: Kind
    view:
        toolbarButtons: create|link|unlink
        form: $/arteriaweb/catalog/models/kind/fields_kind_filtered.yaml
    manage:
        form: $/arteriaweb/catalog/models/kind/fields.yaml
        list: $/arteriaweb/catalog/models/kind/columns.yaml

size:
    label: Size
    view:
        list: $/arteriaweb/catalog/models/size/columns.yaml
        toolbarButtons: create|delete
    manage:
        form: $/arteriaweb/catalog/models/size/fields.yaml
        list: $/arteriaweb/catalog/models/size/columns.yaml
